name: CI-Pipeline pyhton 3.9.8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: heroku container:login
      - run: docker build --build-arg COPY_DIR=capstone_project -t flower-predict -f capstone_project/Dockerfile .

