name: CI-Pipeline pyhton 3.9.8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: echo "HELLO"

